// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bwiejzcoumsqqtoyxpnz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ3aWVqemNvdW1zcXF0b3l4cG56Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM4NzAyNjAsImV4cCI6MjA2OTQ0NjI2MH0.JhHhILiXO0h8qCqQfhiXOphwnozMHYdH4Hs0A9nSF9w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});