// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zxoxgpulkxjmawgumssp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp4b3hncHVsa3hqbWF3Z3Vtc3NwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQyMjU3MDUsImV4cCI6MjA2OTgwMTcwNX0.wlQe3D9tYktHn6H1Ff9hb6TNDJIBvJMI2CzH0Dfv-kE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});